  spring:
    datasource:
      url: jdbc:h2:tcp://localhost/~/test
      username: sa
      password:
      driver-class-name: org.h2.Driver


    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          format_sql: true
    mail:
      host: smtp.gmail.com
      port: 587
      username: giarmri@gmail.com
      password: tlsrn157
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true

  logging.level:
    org.hibernate.SQL: trace

  server:
    servlet:
      session:
        tracking-modes: cookie