spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  servlet:
    multipart:
      location: ~/upload
      maxFileSize: 100MB
      maxRequestSize: 100MB


  jpa:
    hibernate:
      ddl-auto:update
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: giarmri@gmail.com
    password: tlsrn157
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: giarmri@gmail.com
    password: tlsrn157
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  server:
    servlet:
      session:
        tracking-modes: cookie

  com:
    SpringIsComing:
      injagang:
        upload:
          path: C:/Users/roe96/upload